name: lucide_icons_flutter
description: A Lucide icon library package for Flutter applications. Fork of Feather Icons, open for anyone to contribute icons.
version: 1.0.2
homepage: https://lucide.dev
repository: https://github.com/lucide-icons/lucide

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^4.1.0
  lint: ^2.2.0

flutter:
  fonts:
    - family: Lucide
      fonts:
        - asset: assets/lucide.ttf 
# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: